MaxEventSize: 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data
Writable:
  LogLevel: INFO

Service:
  Host: localhost
  Port: 59900
  StartupMsg: device virtual started

MessageBus:
  Optional:
    ClientId: device-virtual

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"